debugmode: true
port: 9102
  #enable_controller: true
metrics:
  probes:
  - name: conntrack
  - name: qdisc
  - name: netdev
  - name: io
  - name: sock
  - name: tcpsummary
  - name: tcp
  - name: tcpext
  - name: udp
  - name: kernellatency
  - name: packetloss
  - name: flow
event:
  probes: 
  - name: biolatency
  - name: kernellatency
  - name: packetloss
  - name: tcpreset
  sinks: []
  
  

